name = "pawapol"
compatibility_date = "2024-01-01"

# Required for Next.js / next-on-pages
compatibility_flags = ["nodejs_compat"]

# Pages build output (next-on-pages uses this)
pages_build_output_dir = ".vercel/output/static"

# Optional but recommended
# Keeps Workers runtime consistent
node_compat = true
